apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: flask-app-secret
  namespace: default
spec:
  encryptedData:
    SECRET: AgBhhbWFAG98nSDKI5DoTJjEeao4KuWy6a+zzs7AFXg6NXXbdbaA/zH7u2a5EPuJnVnk6/ORB/AiBwaALdTJj4BFltu040Wx6iCAOyilRPgBqyAFYM/ZCsgzoeLHNto+8zKedGmxlJNSWTjgS9xYER51SdsBx5zq18xkGoMEyisLQFuKmunl1jJY4Z+0UacHzy6EFHM5d89IMddwvXtIMREmfzFkt5Svoh2XxeucxGFASJQ3VueLZHSYovt5I7ZNEFQHHU1PjN3iRdY0V5Cp93Po3c5iRH78aAV37dqbT3Rwyco6nhGRG7re7gAKEzTzfrMBBXfiIywz38+zka5pTMwj8+sp5F0g3o9jICSf/dm3UYRouf2q1Cd6me+VUbzQ2dTQSCrZyEMOKQaBsf1vVnYsFyHoq78eIqJlaFMXjDt4Q9tGbGoraJr/nhVuWgmWpcVKZO9T1NotW5gVQkjh/PcUz+25GEXIRhGqhwewubt3kG7c6KMCqt9pCKZMVJ4nuCMRf4kAi+Y9VLeDvb8faYqy75NbrqWyji1gnfUl9QhJ6BVREn09us+UahQEVnWG+zE4bRx9FWM7zEokOs0ttIhOViQ0tYjPn1U3Z/cdEqcZQhLR0g2/gkyUyp/qHLupNWk3V5jp9AzXkxcExY7rQrvsIKRLZod143TSqIO/pPWxwn+3Bv8zSvoZfgPr1b1B5s5ItlhrJOk=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: flask-app-secret
      namespace: default

