name: Create Kubernetes Cluster
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Terraform
      id: install-terraform
      run: wget -O terraform.zip https://releases.hashicorp.com/terraform/0.15.3/terraform_0.15.3_linux_amd64.zip && unzip terraform.zip && chmod +x terraform && mv terraform /usr/local/bin
    - name: Send key to file
      id: fetch-key
      run: echo ${{ secrets.GCP_CREDENTIALS  }} >> credentials.json
    - name: Apply Terraform
      id: apply-terraform
      run: terraform apply --auto-approve